# Use the official Node.js Alpine image as base
FROM node:alpine as development

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json .
COPY package-lock.json .

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that the development server will run on
EXPOSE 5173

# Start the development server
CMD ["npm", "run", "dev"]

