version: '3'
services:
  blogger:
    image: blogger
    build:
      context: ./backend
      dockerfile: dockerfile
      target: development
    restart: always
    command: npm run start:dev
    env_file: ./backend/.env
    ports:
      - '3000:3000'
  react-blog:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
